import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { QueryProvider } from '@/providers/query-provider';
import { SheetProvider } from '@/providers/sheet-provider';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Denolo Latest-Test',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} bg-slate-100 min-h-screen w-full flex flex-col`}
			>
				<QueryProvider>
					<Header />
					<main className="flex-auto max-w-5xl mx-auto  w-full">
					<SheetProvider />
					<Toaster />
						{children}</main>
					<Footer />
				</QueryProvider>
			</body>
		</html>
	);
}
